In [1]:
import numpy as np 
import pandas as pd 
cleaning_df = pd.read_csv("dataset_tp_cleaning.csv")
cleaning_df.describe()

,customer_id,full_name,email,age,gender,city,country,signup_date,annual_income_eur,monthly_spend_eur,tenure_months,plan,payment_method,device,satisfaction_score,support_tickets_12m,last_login,marketing_opt_in,churned
count,9965,10000,9901,9795,10000,9861,10000,10000,9715,9812,10000,10000,9902,10000,9797,10000,9839,10000,10000
unique,9716,665,8705,73,17,62,22,2830,9121,5242,174,18,20,14,33,34,8980,14,12
top,CUST-007925,Emma Durand,invalid-email,18,Male,Toulouse,France,99/99/9999,15000,?,36,Basic,Card,Mobile,7,0,?,Yes,No
freq,2,37,37,622,4690,1638,8500,21,224,31,170,3960,4058,6203,2184,5884,19,5384,8419

In [3]:
print("Dimensions :", cleaning_df.shape)
print("\nTypes des variables :")
cleaning_df.info()

print("\nStatistiques descriptives :")
display(cleaning_df.describe(include="all").T)

print("\nNoms des colonnes :")
print(cleaning_df.columns.tolist())

Dimensions : (10000, 19)

Types des variables :
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          9965 non-null   str
 1   full_name            10000 non-null  str
 2   email                9901 non-null   str
 3   age                  9795 non-null   str
 4   gender               10000 non-null  str
 5   city                 9861 non-null   str
 6   country              10000 non-null  str
 7   signup_date          10000 non-null  str
 8   annual_income_eur    9715 non-null   str
 9   monthly_spend_eur    9812 non-null   str
 10  tenure_months        10000 non-null  str
 11  plan                 10000 non-null  str
 12  payment_method       9902 non-null   str
 13  device               10000 non-null  str
 14  satisfaction_score   9797 non-null   str
 15  support_tickets_12m  10000 non-null  str
 16  last_login           9839 non-null   str
 17  marketing_opt_in     10000 non-null  str
 18  churned              10000 non-null  str
dtypes: str(19)
memory usage: 2.8 MB

Statistiques descriptives :

                     count unique            top  freq
customer_id           9965   9716    CUST-007925     2
full_name            10000    665    Emma Durand    37
email                 9901   8705  invalid-email    37
age                   9795     73             18   622
gender               10000     17           Male  4690
city                  9861     62       Toulouse  1638
country              10000     22         France  8500
signup_date          10000   2830     99/99/9999    21
annual_income_eur     9715   9121          15000   224
monthly_spend_eur     9812   5242              ?    31
tenure_months        10000    174             36   170
plan                 10000     18          Basic  3960
payment_method        9902     20           Card  4058
device               10000     14         Mobile  6203
satisfaction_score    9797     33              7  2184
support_tickets_12m  10000     34              0  5884
last_login            9839   8980              ?    19
marketing_opt_in     10000     14            Yes  5384
churned              10000     12             No  8419

Noms des colonnes :
['customer_id', 'full_name', 'email', 'age', 'gender', 'city', 'country', 'signup_date', 'annual_income_eur', 'monthly_spend_eur', 'tenure_months', 'plan', 'payment_method', 'device', 'satisfaction_score', 'support_tickets_12m', 'last_login', 'marketing_opt_in', 'churned']

In [4]:
missing = pd.DataFrame({
    "nb_manquants": cleaning_df.isna().sum(),
    "pct_manquants": cleaning_df.isna().mean() * 100
})

missing = missing.sort_values(
    "pct_manquants",
    ascending=False
)

display(missing)

                     nb_manquants  pct_manquants
annual_income_eur             285           2.85
age                           205           2.05
satisfaction_score            203           2.03
monthly_spend_eur             188           1.88
last_login                    161           1.61
city                          139           1.39
email                          99           0.99
payment_method                 98           0.98
customer_id                    35           0.35
full_name                       0           0.00
country                         0           0.00
tenure_months                   0           0.00
signup_date                     0           0.00
gender                          0           0.00
plan                            0           0.00
device                          0           0.00
support_tickets_12m             0           0.00
marketing_opt_in                0           0.00
churned                         0           0.00

In [5]:
print("Nombre de lignes dupliquées :", cleaning_df.duplicated().sum())

display(cleaning_df[cleaning_df.duplicated(keep=False)].head(20))

Nombre de lignes dupliquées : 250

,customer_id,full_name,email,age,gender,city,country,signup_date,annual_income_eur,monthly_spend_eur,tenure_months,plan,payment_method,device,satisfaction_score,support_tickets_12m,last_login,marketing_opt_in,churned
28,CUST-007925,Arthur Dubois,arthur.dubois68@example.com,51,Female,Paris,France,2025-01-18,"20,172",38.61,20,Premium,Bank Transfer,Mobile,7,4,2026-09-23 01:26:00,Yes,No
75,CUST-008722,Camille Moreau,camille.moreau89@example.com,43,female,Lyon,france,2024-06-27,33360.82,32.62,27,Standard,Card,Mobile,9,0,2026-08-20 07:51:00,No,No
124,CUST-001773,Nina Fournier,nina.fournier27@example.com,26,Male,Montpellier,France,2022-07-06,24558.98,41.71,51,Standard,Direct Debit,Mobile,7,0,2026-09-23 01:10:00,No,No
139,CUST-000801,Lucas Durand,lucas.durand25@example.com,61,Male,Paris,France,2022-01-12,17864.37,39.97,57,Standard,Card,Mobile,8,2,2026-09-10 04:07:00,No,No
158,CUST-009531,Nathan Lefebvre,nathan.lefebvre25@example.com,48,Male,Montpellier,France,2024-01-17,26622.88,32.41,32,Standard,Card,Desktop,8,1,2026-08-17 07:14:00,Yes,No
163,CUST-009225,Emma Durand,emma.durand10@example.com,40,Male,Bordeaux,Spain,2022-10-06,53346.97,54.74,48,Standard,Card,Desktop,9,0,2026-08-20 14:55:00,No,No
170,CUST-003540,Jade Michel,jade.michel48@example.com,38,Female,Lyon,France,2024-10-06,28605.91,50.64,24,Standard,Direct Debit,Desktop,6,2,2026-09-05 07:29:00,Yes,No
231,CUST-002582,Rayan Dubois,rayan.dubois60@example.com,19,Male,Toulouse,France,2024-07-07,19051.02,38.07,27,Starter,Direct Debit,Mobile,5,5,2026-09-02 13:05:00,Yes,No
266,CUST-008972,Louis Martin,louis.martin48@example.com,42,Female,Paris,France,2021-03-14,26444.2,48.77,67,Standard,PayPal,Mobile,9,0,2026-09-28 13:19:00,Yes,No
272,CUST-006230,Yanis Fournier,yanis.fournier22@example.com,32,Male,Paris,France,2026-01-12,21714.11,61.11,9,Standard,PayPal,Desktop,7,0,2026-09-04 16:30:00,Yes,No
289,CUST-002454,Rayan Laurent,rayan.laurent29@example.com,18,Male,Nice,FRANCE,2025-12-31,21143.53,41.36,9,Basic,Bank Transfer,Tablet,9,0,2026-09-14 19:43:00,Yes,No
300,CUST-000929,Sofia Bernard,sofia.bernard56@example.com,31,Male,Marseille,France,2026-02-09,35647.03,41.8,8,Standard,Card,Mobile,8,2,2026-07-28 02:43:00,No,Yes
367,CUST-006854,Tom Garcia,tom.garcia64@example.com,35,Male,Bordeaux,France,2021-03-30,38134.28,62.19,66,Standard,Direct Debit,Tablet,?,0,2026-09-20 23:20:00,Yes,No
392,CUST-000271,Eva Martin,eva.martin77@example.com,23,Female,Paris,France,2022-09-09,64301.74,46.32,49,Basic,PayPal,Desktop,8,0,2026-09-15 11:01:00,Yes,No
448,CUST-006880,Louis Simon,louis.simon90@example.com,64,Male,Montpellier,Germany,2020-11-20,28307.53,28.37,70,Standard,Card,Desktop,10,0,2026-08-31 17:27:00,No,No
495,CUST-007550,Adam Laurent,adam.laurent81@example..com,40,Female,LILLE,France,2026-01-06,64186.1,37.84,9,Basic,Bank Transfer,Tablet,6,2,2026-08-26 14:43:00,false,No
510,CUST-008997,Noah Roux,noah.roux73@example.com,36,Male,Lyon,France,2022-07-15,28799.7,45.01,51,Standard,Direct Debit,Tablet,7,1,06-08-2026 01:04 AM,Yes,Yes
511,CUST-009733,Louis Martin,louis.martin33@example.com,46,Male,Bordeaux,Spain,11/07/2021,24740.31,53.89,63,Premium,Direct Debit,Desktop,6,0,2026-08-29 03:32:00,Yes,No
527,CUST-004516,Inès Petit,ines.petit54@example.com,38,Female,Grenoble,France,2021-12-01,27174.35,66.96,58,Premium,Bank Transfer,Mobile,5,3,2026-09-01 13:14:00,Yes,No
532,CUST-001570,Adam Vincent,adam.vincent18@example.com,42,Male,Strasbourg,France,2023-06-26,51551.23,60.98,39,Standard,Card,Mobile,7,0,2026-08-26 22:32:00,Yes,No

In [6]:
display(pd.DataFrame({
    "type": cleaning_df.dtypes.astype(str),
    "valeurs_uniques": cleaning_df.nunique(dropna=True),
    "manquants": cleaning_df.isna().sum()
}))

                    type  valeurs_uniques  manquants
customer_id          str             9716         35
full_name            str              665          0
email                str             8705         99
age                  str               73        205
gender               str               17          0
city                 str               62        139
country              str               22          0
signup_date          str             2830          0
annual_income_eur    str             9121        285
monthly_spend_eur    str             5242        188
tenure_months        str              174          0
plan                 str               18          0
payment_method       str               20         98
device               str               14          0
satisfaction_score   str               33        203
support_tickets_12m  str               34          0
last_login           str             8980        161
marketing_opt_in     str               14          0
churned              str               12          0

In [8]:
for col in cleaning_df.select_dtypes(include="object").columns:
    print(f"\n--- {col} ---")
    print(cleaning_df[col].value_counts(dropna=False).head(20))

C:\Users\izedi\AppData\Local\Temp\ipykernel_18724\3260356726.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in cleaning_df.select_dtypes(include="object").columns:

--- customer_id ---
customer_id
NaN            35
CUST-007925     2
CUST-008722     2
CUST-001773     2
CUST-000801     2
CUST-009531     2
CUST-009225     2
CUST-003540     2
CUST-002582     2
CUST-008972     2
CUST-006230     2
CUST-002454     2
CUST-000929     2
CUST-006854     2
CUST-000271     2
CUST-006880     2
CUST-007550     2
CUST-008997     2
CUST-009733     2
CUST-004516     2
Name: count, dtype: int64

--- full_name ---
full_name
Emma Durand         37
Noah Lefebvre       35
Nina David          35
Noah Fournier       35
Louis Moreau        32
Yanis Thomas        32
Gabriel Bertrand    31
Louise Petit        31
Emma Laurent        31
Hugo Lefebvre       31
Adam Michel         29
Léa Thomas          29
Lucas Michel        29
Gabriel Laurent     29
Gabriel Moreau      29
Jade David          29
Camille Laurent     29
Nina Michel         29
Eva Martin          29
Eva Simon           29
Name: count, dtype: int64

--- email ---
email
NaN                              99
invalid-email                    37
?                                18
yanis.fournier22@example.com      4
hugo.michel84@example.com         4
camille.durand18@example.com      4
rayan.david86@example.com         4
louise.thomas22@example.com       4
louis.roux4@example.com           4
nathan.lefebvre45@example.com     4
noah.richard80@example.com        4
louis.david7@example.com          4
nathan.david13@example.com        4
tom.dubois50@example.com          3
louise.bertrand15@example.com     3
sarah.laurent4@example.com        3
tom.durand36@example.com          3
camille.moreau89@example.com      3
jade.laurent42@example.com        3
nathan.lefebvre25@example.com     3
Name: count, dtype: int64

--- age ---
age
18    622
37    316
44    313
40    313
38    305
41    298
36    297
43    297
39    289
35    279
33    278
42    272
34    271
48    269
45    263
32    258
31    250
46    247
27    225
47    219
Name: count, dtype: int64

--- gender ---
gender
Male            4690
Female          4567
Non-binary       196
femme             61
female            59
 FEMALE           58
F                 57
Man               56
homme             55
Woman             53
male              49
M                 48
 MALE             39
non binary         4
NB                 3
NonBinary          3
 non-binary        2
Name: count, dtype: int64

--- city ---
city
Toulouse       1638
Paris          1486
Lyon            923
Bordeaux        752
Marseille       718
Montpellier     658
Lille           646
Nantes          616
Rennes          449
Strasbourg      446
Nice            423
Grenoble        383
NaN             139
?                39
PARIS            36
Tlse             33
 Toulouse        32
Touluse          27
paris            25
MARSEILLE        24
Name: count, dtype: int64

--- country ---
country
France       8500
Belgium       330
Spain         302
Germany       285
Italy         235
 France        64
Fr             62
FRANCE         58
france         56
FR             55
italy           7
Belgique        6
belgium         6
ES              5
spain           5
IT              5
DE              4
Italie          4
germany         3
Allemagne       3
Name: count, dtype: int64

--- signup_date ---
signup_date
99/99/9999    21
2026-13-01    15
2024-05-23    13
31/02/2025    13
2022-03-03    13
2024-03-28    12
2025-09-17    12
2024-01-01    12
2026-01-08    12
2024-05-25    12
2024-09-19    11
2020-12-28    11
2022-10-06    11
2023-10-07    11
2021-05-09    11
not_a_date    11
2023-03-11    10
2021-02-20    10
2021-04-07    10
2025-11-14    10
Name: count, dtype: int64

--- annual_income_eur ---
annual_income_eur
NaN         285
15000       224
?            57
1200000      16
9999999      16
-25000       15
0            12
34.4k         3
32948.2       3
31.3k         2
20,172        2
57.3k         2
33360.82      2
24558.98      2
17864.37      2
26622.88      2
53346.97      2
28605.91      2
19051.02      2
26444.2       2
Name: count, dtype: int64

--- monthly_spend_eur ---
monthly_spend_eur
NaN      188
?         31
5         21
1500      20
-99       18
5000      13
0         10
50.15      9
49.89      8
42.08      8
40.2       8
36.54      8
52.56      8
42.59      8
57.03      7
47.9       7
37.77      7
50.88      7
40.41      7
44.13      7
Name: count, dtype: int64

--- tenure_months ---
tenure_months
36    170
43    159
57    156
28    153
9     153
42    153
65    152
32    151
69    151
13    150
68    148
47    148
48    147
16    147
17    146
20    145
14    145
24    145
37    145
21    144
Name: count, dtype: int64

--- plan ---
plan
Basic         3960
Standard      3607
Premium       1845
Starter         58
Std             55
STANDARD        54
 BASIC          52
Basic Plan      51
basic           50
 Standard       47
standard        46
 Premium        37
PREMIUM         36
Pro             35
premium         26
Gold            17
VIP             13
Unknown         11
Name: count, dtype: int64

--- payment_method ---
payment_method
Card             4058
PayPal           1887
Bank Transfer    1858
Direct Debit     1635
NaN                98
CB                 53
Credit Card        51
 CARD              50
card               47
paypal             33
Pay Pal            30
PAYPAL             27
?                  22
SEPA               22
Wire               20
BANK TRANSFER      20
bank transfer      19
direct debit       19
DirectDebit        18
BankTransfer       17
Name: count, dtype: int64

--- device ---
device
Mobile        6203
Desktop       2567
Tablet         877
MOBILE          65
 phone          63
mobile          61
Smartphone      44
desktop         24
DESKTOP         23
PC              22
 computer       16
Tab             13
TABLET          11
tablet          11
Name: count, dtype: int64

--- satisfaction_score ---
satisfaction_score
7       2184
8       1953
6       1752
9       1350
5        943
10       800
4        397
NaN      203
3        122
?         44
2         27
8/10      20
7/10      19
6/10      18
 9        17
 7        17
 8        16
20        15
 6        14
bad       13
Name: count, dtype: int64

--- support_tickets_12m ---
support_tickets_12m
0            5884
1            1992
2             884
3             464
4             239
5             143
6              86
7              68
8              35
0 tickets      31
 0             27
10             20
250            17
-2             14
9              10
 1             10
99             10
11             10
12              8
 2              6
Name: count, dtype: int64

--- last_login ---
last_login
NaN                    161
?                       19
32/01/2026              16
2026-99-99              12
not available           12
2026-08-19               8
2026-09-12               7
2026-08-17               6
2026-09-16               6
2026-09-18               5
2026-09-13               5
2026-09-24               5
2026-09-15               4
2026-08-27 09:43:00      4
2026-09-27               4
2026-09-22               4
2026-09-01               4
2026-08-30               4
2026-08-24               4
2026-09-26               4
Name: count, dtype: int64

--- marketing_opt_in ---
marketing_opt_in
Yes        5384
No         3914
 true        88
YES          74
True         69
yes          62
Y            60
1            57
0            56
N            49
 false       49
NO           48
False        47
no           43
Name: count, dtype: int64

--- churned ---
churned
No       8419
Yes      1335
0          61
no         39
NO         35
N          34
False      29
1          14
YES        10
Y           9
True        8
yes         7
Name: count, dtype: int64

In [11]:
df_raw = cleaning_df.copy(deep=True)
df_clean = cleaning_df.copy(deep=True)

In [12]:
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", "_", regex=True)
)

In [13]:
for col in df_clean.select_dtypes(include="object").columns:
    df_clean[col] = df_clean[col].str.strip()

C:\Users\izedi\AppData\Local\Temp\ipykernel_18724\1854410094.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_clean.select_dtypes(include="object").columns:

In [14]:
nb_doublons = int(df_clean.duplicated().sum())

df_clean = df_clean.drop_duplicates()

print("Lignes dupliquées supprimées :", nb_doublons)

Lignes dupliquées supprimées : 250

In [15]:
num_cols = df_clean.select_dtypes(
    include="number"
).columns

for col in num_cols:
    if df_clean[col].isna().any():
        mediane = df_clean[col].median()
        print(f"{col} : médiane utilisée = {mediane}")

In [16]:
for col in num_cols:
    if df_clean[col].isna().any():
        df_clean[col] = df_clean[col].fillna(
            df_clean[col].median()
        )

In [17]:
def detecter_outliers_iqr(data, colonne):
    q1 = data[colonne].quantile(0.25)
    q3 = data[colonne].quantile(0.75)
    iqr = q3 - q1

    borne_inf = q1 - 1.5 * iqr
    borne_sup = q3 + 1.5 * iqr

    masque = (
        (data[colonne] < borne_inf) |
        (data[colonne] > borne_sup)
    )

    return data.loc[masque], borne_inf, borne_sup


# Exemple :
# outliers, borne_inf, borne_sup = detecter_outliers_iqr(
#     df_clean, "montant"
# )
# display(outliers)

In [20]:

from pathlib import Path

# Créer un dossier pour les données nettoyées
OUTPUT_DIR = Path("data/processed")

print("Dossier de sortie :", OUTPUT_DIR.resolve())

Dossier de sortie : C:\Users\izedi\Downloads\projet data\data\processed

In [21]:


OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Exporter le DataFrame nettoyé
df_clean.to_csv(
    OUTPUT_DIR / "dataset_tp_cleaning.csv",
    index=False,
    encoding="utf-8"
)

print("Fichier exporté :", (OUTPUT_DIR / "dataset_tp_cleaning.csv").resolve())

Fichier exporté : C:\Users\izedi\Downloads\projet data\data\processed\dataset_tp_cleaning.csv

In [22]:

# Vérifier l'existence du fichier
fichier = OUTPUT_DIR / "dataset_tp_cleaning.csv"

print("Fichier créé :", fichier.exists())

# Vérifier les dimensions des données exportées
df_verification = pd.read_csv(fichier)
print("Dimensions du fichier exporté :", df_verification.shape)

display(df_verification.head())

Fichier créé : True
Dimensions du fichier exporté : (9750, 19)

,customer_id,full_name,email,age,gender,city,country,signup_date,annual_income_eur,monthly_spend_eur,tenure_months,plan,payment_method,device,satisfaction_score,support_tickets_12m,last_login,marketing_opt_in,churned
0,CUST-004845,Adam Michel,adam.michel92@example.com,58,Female,Paris,France,2024-12-18,23572.23,33.78,21,STANDARD,Bank Transfer,Desktop,7,2,2026-09-07 10:54:00,No,No
1,CUST-000374,Rayan Thomas,rayan.thomas83@example.com,44,Male,Nantes,France,2023-10-16,39185.36,41.1,36,Standard,Card,Mobile,6,6,2026-02-27 19:40:00,No,Yes
2,CUST-005953,Inès Garcia,ines.garcia36@example.com,36,Female,Lyon,France,2025-12-06,28278.13,15.25,10,Basic,Card,Smartphone,8,0,2026-08-26 21:21:00,Yes,Yes
3,CUST-009007,Lucas Richard,lucas.richard83@example.com,44,Female,Lyon,France,2024-02-15,30721.31,48.8,32,Std,Card,Mobile,8,1,2026-09-26 06:15:00,N,No
4,CUST-007822,Hugo Laurent,hugo.laurent62@example.com,41,Female,Toulouse,France,2022-06-27,61258.15,52.95,51,Basic,Card,Mobile,7,0,2026-02-15 08:22:00,No,1

In [23]:
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

df_clean.to_csv(
    OUTPUT_DIR / "dataset_tp_cleaning.csv",
    index=False
)

print("Dimensions initiales :", df_raw.shape)
print("Dimensions finales :", df_clean.shape)

Dimensions initiales : (10000, 19)
Dimensions finales : (9750, 19)

In [24]:
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# Style des graphiques
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (9, 5)

# Vérifier les données
print("Dimensions :", cleaning_df.shape)
print("Colonnes disponibles :", cleaning_df.columns.tolist())

Matplotlib is building the font cache; this may take a moment.

Dimensions : (10000, 19)
Colonnes disponibles : ['customer_id', 'full_name', 'email', 'age', 'gender', 'city', 'country', 'signup_date', 'annual_income_eur', 'monthly_spend_eur', 'tenure_months', 'plan', 'payment_method', 'device', 'satisfaction_score', 'support_tickets_12m', 'last_login', 'marketing_opt_in', 'churned']